version: "3.8"

services:

  catalog-service:
    depends_on:
      - bookshop-postgres
    image: "my-catalog-service"
    container_name: "my-catalog-service"
    ports:
      - 9001:9001
      - 8001:8001
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8001
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_DATASOURCE_URL=jdbc:postgresql://bookshop-postgres:5432/bookshopdb_catalog
      - SPRING_PROFILES_ACTIVE=testdata
  bookshop-postgres:
    image: "postgres:14.10"
    container_name: "bookshop-postgres"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=bookshopdb_catalog

